/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCardSignup: typeof import('./src/components/BaseCardSignup.vue')['default']
    BaseCodeExample: typeof import('./src/components/BaseCodeExample.vue')['default']
    BaseContact: typeof import('./src/components/BaseContact.vue')['default']
    BaseCountrySelect: typeof import('./src/components/BaseCountrySelect.vue')['default']
    BaseDemoDescription: typeof import('./src/components/BaseDemoDescription.vue')['default']
    BaseFeatures: typeof import('./src/components/BaseFeatures.vue')['default']
    BaseJumbotron: typeof import('./src/components/BaseJumbotron.vue')['default']
    BaseJumbotronDemo: typeof import('./src/components/demo/BaseJumbotronDemo.vue')['default']
    BaseJumbotronTokenLaunch: typeof import('./src/components/token/BaseJumbotronTokenLaunch.vue')['default']
    BaseMetrics: typeof import('./src/components/BaseMetrics.vue')['default']
    BaseNavbar: typeof import('./src/components/BaseNavbar.vue')['default']
    BaseNoCode: typeof import('./src/components/BaseNoCode.vue')['default']
    BasePartners: typeof import('./src/components/BasePartners.vue')['default']
    BaseTeam: typeof import('./src/components/BaseTeam.vue')['default']
    BaseTechnologies: typeof import('./src/components/BaseTechnologies.vue')['default']
    BaseTestimonials: typeof import('./src/components/BaseTestimonials.vue')['default']
    BaseTokenBenefits: typeof import('./src/components/token/BaseTokenBenefits.vue')['default']
    BaseTokenCirculation: typeof import('./src/components/token/BaseTokenCirculation.vue')['default']
    BaseTokenContract: typeof import('./src/components/token/BaseTokenContract.vue')['default']
    BaseTokenDistribution: typeof import('./src/components/token/BaseTokenDistribution.vue')['default']
    BaseTokenLaunchSubscribe: typeof import('./src/components/token/BaseTokenLaunchSubscribe.vue')['default']
    BaseUseCaseContact: typeof import('./src/components/BaseUseCaseContact.vue')['default']
    BaseUseCases: typeof import('./src/components/BaseUseCases.vue')['default']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next')['BFormInvalidFeedback']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BLink: typeof import('bootstrap-vue-next')['BLink']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    ModalSubscribe: typeof import('./src/components/ModalSubscribe.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
