/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BaseCardCollectionMetadata: typeof import('./src/components/BaseCardCollectionMetadata.vue')['default']
    BaseCardProfile: typeof import('./src/components/BaseCardProfile.vue')['default']
    BaseCardTableHeader: typeof import('./src/components/BaseCardTableHeader.vue')['default']
    BaseFormCollectionMetadata: typeof import('./src/components/BaseFormCollectionMetadata.vue')['default']
    BaseFormCollectionMetadataQRCodes: typeof import('./src/components/BaseFormCollectionMetadataQRCodes.vue')['default']
    BaseFormGroup: typeof import('./src/components/BaseFormGroup.vue')['default']
    BaseFormInputFile: typeof import('./src/components/BaseFormInputFile.vue')['default']
    BaseHrOrSeparator: typeof import('./src/components/BaseHrOrSeparator.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BAvatar: typeof import('bootstrap-vue-next')['BAvatar']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
    BLink: typeof import('bootstrap-vue-next')['BLink']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BPlaceholder: typeof import('bootstrap-vue-next')['BPlaceholder']
    BPlaceholderCard: typeof import('bootstrap-vue-next')['BPlaceholderCard']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBClipboard: typeof import('bootstrap-vue-next')['vBClipboard']
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
