export const AUTH_URL = process.env.VUE_APP_AUTH_URL;
export const API_URL = process.env.VUE_APP_API_URL || '';
export const WIDGET_URL = process.env.VUE_APP_WIDGET_URL || '';
export const CLIENT_ID = process.env.VUE_APP_CLIENT_ID || '';
export const CLIENT_SECRET = process.env.VUE_APP_CLIENT_SECRET || '';
export const PKG_ENV = process.env.VUE_APP_PKG_ENV || 'prod';
export const GTM = process.env.VUE_APP_GTM || '';
export const MIXPANEL_TOKEN = process.env.VUE_APP_MIXPANEL_TOKEN || '';
export const STRIPE_PUBLISHABLE_TEST_KEY = process.env.VUE_APP_STRIPE_PUBLISHABLE_TEST_KEY || '';
