/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BaseCardBodyCollectible: typeof import('./src/components/BaseCardBodyCollectible.vue')['default']
    BaseCardCollapseCollectible: typeof import('./src/components/BaseCardCollapseCollectible.vue')['default']
    BaseDropdownWallets: typeof import('./src/components/BaseDropdownWallets.vue')['default']
    BaseFormGroup: typeof import('./src/components/BaseFormGroup.vue')['default']
    BaseHrOrSeparator: typeof import('./src/components/BaseHrOrSeparator.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BaseModalLogin: typeof import('./src/components/BaseModalLogin.vue')['default']
    BaseModalWalletCreate: typeof import('./src/components/BaseModalWalletCreate.vue')['default']
    BaseModalWalletRecovery: typeof import('./src/components/BaseModalWalletRecovery.vue')['default']
    BaseModalWalletSafe: typeof import('./src/components/BaseModalWalletSafe.vue')['default']
    BaseTabWalletVariant: typeof import('./src/components/BaseTabWalletVariant.vue')['default']
    BaseTabWalletWalletConnect: typeof import('./src/components/BaseTabWalletWalletConnect.vue')['default']
    BaseTabWalletWeb3Auth: typeof import('./src/components/BaseTabWalletWeb3Auth.vue')['default']
    BAvatar: typeof import('bootstrap-vue-next')['BAvatar']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BLink: typeof import('bootstrap-vue-next')['BLink']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
